{{- $root := . -}}
{{- range $i := until (int .Values.replicaCount) }}
{{- $nodeIndex := add $i 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: nccl-host-{{ $nodeIndex }}
spec:
  selector:
    name: nccl-host-{{ $nodeIndex }}
  clusterIP: None
{{- end }}
