{{- $root := . -}}
{{- $replicaCount := .Values.replicaCount -}}
{{- range $i := until (int $replicaCount) }}
{{- $nodeIndex := add $i 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $root.Release.Name }}-{{ $nodeIndex }}
spec:
  selector:
    name: {{ $root.Release.Name }}-{{ $nodeIndex }}
  clusterIP: None
{{- end }}
