apiVersion: v1
kind: PersistentVolume
metadata:
  name: cfs-pv
spec:
  storageClassName: ""
  capacity:
    storage: 10Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    volumeHandle: "modeInstance/us-central1-b/nfs-poc/cfs"
    volumeAttributes:
      ip: 10.175.64.2
      volume: cfs
  claimRef:
    name: cfs-pvc
    namespace: default
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cfs-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Ti
