apiVersion: v1
kind: Service
metadata:
  name: ubuntu-1
spec:
  selector:
    name: ubuntu-1
  clusterIP: None
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-1
  labels:
    name: ubuntu-1
  annotations:
    networking.gke.io/default-interface: 'eth0'
    kueue.x-k8s.io/podset-preferred-topology: "kubernetes.io/hostname"
    gke-gcsfuse/volumes: "true"
    gke-gcsfuse/cpu-limit: "0"
    gke-gcsfuse/memory-limit: "0"
    gke-gcsfuse/ephemeral-storage-limit: "0"
spec:
  hostNetwork: false
  hostPID: false
  serviceAccount: workload-identity-k8s-sa
  volumes:
    - name: library-dir-host
      hostPath:
        path: /home/kubernetes/bin/nvidia
    - name: gib
      hostPath:
        path: /home/kubernetes/bin/gib
    - name: shared-memory
      emptyDir:
        medium: "Memory"
        sizeLimit: 250Gi
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: cfs-pvc
  containers:
    - image: ubuntu:latest
      name: ubuntu
      resources:
        requests:
          cpu: 150m
      volumeMounts:
        - name: library-dir-host
          mountPath: /usr/local/nvidia
        - name: gib
          mountPath: /usr/local/gib
        - name: shared-memory
          mountPath: /dev/shm
        - name: nfs-volume
          mountPath: /cfs
      env:
      command: ["/bin/bash", "-c"]
      args:
        - |      
          sleep infinity
