# Default values for poc-runtime
# This is a YAML-formatted file.
# These are relatively static variables that don't change frequently.

# Container images
images:
  container:
    repository: nvcr.io/nvidia/pytorch
    tag: 25.01-py3
    # repository: us-central1-docker.pkg.dev/tx-poc-250507/tx-poc-repo/tensorrt_llm
    # tag: latest
    pullPolicy: IfNotPresent
  initContainer:
    repository: us-docker.pkg.dev/gce-ai-infra/gpudirect-gib/nccl-plugin-gib-diagnostic
    tag: v1.0.5
    pullPolicy: Always

# Resources for the pods
resources:
  requests:
    cpu: 150m
  limits:
    nvidia.com/gpu: 8